/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kcl-lang.io/kcl-operator/api/kclrun/v1alpha1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "kcl-lang.io/kcl-operator/pkg/client/clientset/versioned/scheme"
)

// KCLRunGetter has a method to return a KCLRunInterface.
// A group's client should implement this interface.
type KCLRunGetter interface {
	KCLRun() KCLRunInterface
}

type KCLRunExpansion interface{}

// KCLRunInterface has methods to work with KCLRun resources.
type KCLRunInterface interface {
	Create(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.CreateOptions) (*v1alpha1.KCLRun, error)
	Update(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.UpdateOptions) (*v1alpha1.KCLRun, error)
	UpdateStatus(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.UpdateOptions) (*v1alpha1.KCLRun, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1alpha1.KCLRun, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.KCLRunList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1alpha1.KCLRun, err error)
	KCLRunExpansion
}

// clusterKCLRun implements KCLRunInterface
type clusterKCLRun struct {
	client rest.Interface
}

// newKCLRun returns a KCLRun
func newKCLRun(c *KCLRunV1alpha1Client) *clusterKCLRun {
	return &clusterKCLRun{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterPolicy, and returns the corresponding clusterPolicy object, and an error if there is any.
func (c *clusterKCLRun) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1alpha1.KCLRun, err error) {
	result = &v1alpha1.KCLRun{}
	err = c.client.Get().
		Resource("kclruns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KCLRun that match those selectors.
func (c *clusterKCLRun) List(ctx context.Context, opts metav1.ListOptions) (result *v1alpha1.KCLRunList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KCLRunList{}
	err = c.client.Get().
		Resource("kclruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterKCLRun.
func (c *clusterKCLRun) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kclruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterPolicy and creates it.  Returns the server's representation of the clusterPolicy, and an error, if there is any.
func (c *clusterKCLRun) Create(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.CreateOptions) (result *v1alpha1.KCLRun, err error) {
	result = &v1alpha1.KCLRun{}
	err = c.client.Post().
		Resource("kclruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterPolicy and updates it. Returns the server's representation of the clusterPolicy, and an error, if there is any.
func (c *clusterKCLRun) Update(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.UpdateOptions) (result *v1alpha1.KCLRun, err error) {
	result = &v1alpha1.KCLRun{}
	err = c.client.Put().
		Resource("kclruns").
		Name(clusterPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterKCLRun) UpdateStatus(ctx context.Context, clusterPolicy *v1alpha1.KCLRun, opts metav1.UpdateOptions) (result *v1alpha1.KCLRun, err error) {
	result = &v1alpha1.KCLRun{}
	err = c.client.Put().
		Resource("kclruns").
		Name(clusterPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterPolicy and deletes it. Returns an error if one occurs.
func (c *clusterKCLRun) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kclruns").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterKCLRun) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kclruns").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterPolicy.
func (c *clusterKCLRun) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1alpha1.KCLRun, err error) {
	result = &v1alpha1.KCLRun{}
	err = c.client.Patch(pt).
		Resource("kclruns").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
